services:
    # Wordpress
    wordpress:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
            - mailhog
        ports:
            - '8000:80'
        restart: always
        volumes: ./:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        networks:
            - mynetwork

    # Database
    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - mynetwork

    # phpMyAdmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        networks:
            - mynetwork

    # Mail
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge

volumes:
    db_data:
